#  .DESCRIPTION
#  Imports and activates my custom "insopti PowerPlan" optimized power plan to enhance system power management.
#  This script downloads a power plan configuration file (.pow) from a GitHub repository,imports the "insopti" power plan, and activates it.
#  All parameters have been carefully reviewed and configured to provide optimal performance and responsiveness.
#  Last Updated: 2026-01-24 | Author: https://guns.lol/inso.vs | For personal use only - Redistribution prohibited.

function insoptiwrht { param([string]$Message, [ConsoleColor]$ForegroundColor = 'White', [switch]$NoNewline); if ($NoNewline) { Write-Host $Message -ForegroundColor $ForegroundColor -NoNewline } else { Write-Host $Message -ForegroundColor $ForegroundColor } }
function Write-Log {param([string]$Type, [string]$Message, [string]$Extra = "", [ConsoleColor]$TypeColor = 'White', [ConsoleColor]$MessageColor = 'White', [ConsoleColor]$ExtraColor = 'White');$insoptitime = Get-Date -Format "HH:mm:ss"; insoptiwrht " [" -ForegroundColor blue -NoNewline; insoptiwrht "$Type" -ForegroundColor $TypeColor -NoNewline; insoptiwrht "] [" -ForegroundColor blue -NoNewline; insoptiwrht "$insoptitime" -ForegroundColor darkgray -NoNewline; insoptiwrht "] " -ForegroundColor blue -NoNewline; insoptiwrht "$Message" -ForegroundColor $MessageColor -NoNewline;if ($Extra -ne "") { insoptiwrht " $Extra" -ForegroundColor $ExtraColor } else { insoptiwrht "" }}
function Show-DynamicCountdown {param([int]$Seconds = 2, [string]$Message = "Continuing", [ConsoleColor]$IconColor = [ConsoleColor]::Yellow, [ConsoleColor]$TextColor = [ConsoleColor]::DarkGray); $insopticursorPos = $Host.UI.RawUI.CursorPosition;for ($insoptii = $Seconds; $insoptii -gt 0; $insoptii--) { $Host.UI.RawUI.CursorPosition = $insopticursorPos; insoptiwrht " [" -NoNewline -ForegroundColor blue; insoptiwrht "~" -NoNewline -ForegroundColor $IconColor; insoptiwrht "] " -NoNewline -ForegroundColor blue; insoptiwrht "$Message in $insoptii second" -NoNewline -ForegroundColor $TextColor; if ($insoptii -gt 1) { insoptiwrht "s" -NoNewline -ForegroundColor $TextColor }; insoptiwrht "...                    " -ForegroundColor $TextColor; Start-Sleep -Seconds 1 };$Host.UI.RawUI.CursorPosition = $insopticursorPos; insoptiwrht "                                                      "; $Host.UI.RawUI.CursorPosition = $insopticursorPos}
function insopti { ;try {
        $insoptibannerScriptPath = "$env:TEMP\PowerPlan-Banner.ps1"; $insoptipowerPlanPath = "$env:TEMP\insopti.pow"; Invoke-WebRequest 'https://github.com/insovs/insopti-PowerPlan/releases/download/v1/PowerPlan-Banner.ps1' -OutFile $insoptibannerScriptPath; . $insoptibannerScriptPath; $insoptiWindow = $Host.UI.RawUI; $insoptiWindow.WindowTitle = "[https://guns.lol/inso.vs] | Import a optimized power plan designed for maximum system responsiveness and the lowest possible latency."; $insoptiWindow.BackgroundColor = "Black"; Clear-Host; banner-PowerPlan
        insoptiwrht " [" -ForegroundColor Blue -NoNewline; insoptiwrht "+" -ForegroundColor Green -NoNewline; insoptiwrht "] " -ForegroundColor Blue -NoNewline; insoptiwrht "Select" -ForegroundColor white -NoNewline; insoptiwrht " the appropriate power plan for your CPU tuning profile:" -ForegroundColor White; insoptiwrht " [" -ForegroundColor Blue -NoNewline; insoptiwrht "+" -ForegroundColor Green -NoNewline; insoptiwrht "] " -ForegroundColor Blue -NoNewline; insoptiwrht "This will" -ForegroundColor white -NoNewline; insoptiwrht " determine how Windows manages your processor frequency.`n" -ForegroundColor White -NoNewline; insoptiwrht "`n [" -ForegroundColor blue -NoNewline; insoptiwrht "1" -ForegroundColor White -NoNewline; insoptiwrht "] " -ForegroundColor blue -NoNewline; insoptiwrht "Static OC mode " -ForegroundColor white -NoNewline; insoptiwrht "(For users with manual fixed CPU frequency and Precision Boost disabled)." -ForegroundColor DarkGray; insoptiwrht " [" -ForegroundColor blue -NoNewline; insoptiwrht "2" -ForegroundColor White -NoNewline; insoptiwrht "] " -ForegroundColor blue -NoNewline; insoptiwrht "Dynamic boost mode " -ForegroundColor white -NoNewline; insoptiwrht "(For all other users with Precision Boost/Turbo BIOS settings enabled (usually by default)." -ForegroundColor DarkGray; insoptiwrht "`n [" -ForegroundColor Blue -NoNewline; insoptiwrht "+" -ForegroundColor Green -NoNewline; insoptiwrht "] " -ForegroundColor Blue -NoNewline; insoptiwrht "Select" -ForegroundColor white -NoNewline; insoptiwrht " an option to continue " -ForegroundColor White -NoNewline; insoptiwrht "[" -ForegroundColor Blue -NoNewline; insoptiwrht "1" -ForegroundColor White -NoNewline; insoptiwrht "/" -ForegroundColor Cyan -NoNewline; insoptiwrht "2" -ForegroundColor White -NoNewline; insoptiwrht "]" -ForegroundColor Blue -NoNewline; insoptiwrht ":" -ForegroundColor Blue -NoNewline; insoptiwrht " " -ForegroundColor DarkGray -NoNewline; $insoptiPlanChoice = Read-Host
        if ($insoptiPlanChoice -eq "1") { $insoptiPlanURL = "https://github.com/insovs/insopti-PowerPlan/releases/download/v1/insopti.pow"; $insoptiPlanName = "insopti PowerPlan" } elseif ($insoptiPlanChoice -eq "2") { $insoptiPlanURL = "https://github.com/insovs/insopti-PowerPlan/releases/download/v1/insopti-idle.pow"; $insoptiPlanName = "insopti-idle" } else { Write-Log -Type "!" -TypeColor Yellow -Message "Invalid choice. Operation cancelled." -MessageColor Yellow; Show-DynamicCountdown -Seconds 2 -Message "Returning to menu"; Clear-Host; insoptiexitmainmenu; return }
        Invoke-WebRequest $insoptiPlanURL -OutFile $insoptipowerPlanPath; Clear-Host; banner-PowerPlan; Write-Log -Type "+" -TypeColor Green -Message "This will go import and activate the optimized '$insoptiPlanName'."; Write-Log -Type "+" -TypeColor Green -Message "The following optimizations will be applied by doing this:"; Write-Log -Type "+" -TypeColor Green -Message "Maximize system performance and responsiveness." -MessageColor DarkGray; Write-Log -Type "+" -TypeColor Green -Message "Disable CPU power throttling and latency mitigation features." -MessageColor DarkGray; Write-Log -Type "+" -TypeColor Green -Message "Optimize USB power management and sleep state settings." -MessageColor DarkGray; insoptiwrht "`n [" -ForegroundColor Blue -NoNewline; insoptiwrht "?" -ForegroundColor green -NoNewline; insoptiwrht "] " -ForegroundColor Blue -NoNewline; insoptiwrht "Import the power plan " -ForegroundColor White -NoNewline; insoptiwrht "? " -ForegroundColor white -NoNewline; insoptiwrht "[" -ForegroundColor Blue -NoNewline; insoptiwrht "Y" -ForegroundColor Green -NoNewline; insoptiwrht "/" -ForegroundColor Cyan -NoNewline; insoptiwrht "N" -ForegroundColor Red -NoNewline; insoptiwrht "]" -ForegroundColor Blue -NoNewline; insoptiwrht ": " -ForegroundColor Blue -NoNewline; $insoptiConfirm = Read-Host
        if ($insoptiConfirm -ne "Y" -and $insoptiConfirm -ne "y") { $Host.UI.RawUI.CursorPosition=@{X=0;Y=($Host.UI.RawUI.CursorPosition.Y - 1)}; Write-Log -Type "!" -TypeColor Yellow -Message "Operation cancelled by user." -MessageColor Yellow; Show-DynamicCountdown -Seconds 2 -Message "Returning to menu"; Clear-Host; insoptiexitmainmenu; return }
        $Host.UI.RawUI.CursorPosition=@{X=0;Y=($Host.UI.RawUI.CursorPosition.Y - 1)}; Write-Log -Type "+" -TypeColor Green -Message "Import of the $insoptiPlanName.. please wait."; powercfg -import $insoptipowerPlanPath | Out-Null; Show-DynamicCountdown -Seconds 2 -Message "Processing"; $insoptiplans = powercfg -list; $insoptifound = $false
        foreach ($insoptiline in $insoptiplans) { if ($insoptiline -match '([a-fA-F0-9\-]{36})') { $insoptiguid = $matches[1]; powercfg -setactive $insoptiguid | Out-Null; Start-Sleep -Milliseconds 500; if ((powercfg -getactivescheme) -match "insopti") { $Host.UI.RawUI.CursorPosition=@{X=0;Y=($Host.UI.RawUI.CursorPosition.Y - 1)}; insoptiwrht " [" -NoNewline -ForegroundColor blue; insoptiwrht "+" -NoNewline -ForegroundColor Green; insoptiwrht "] [" -NoNewline -ForegroundColor blue; insoptiwrht "$(Get-Date -Format 'HH:mm:ss')" -NoNewline -ForegroundColor darkgray; insoptiwrht "] " -NoNewline -ForegroundColor blue; insoptiwrht "$insoptiPlanName" -NoNewline -ForegroundColor Blue; insoptiwrht " successfully " -NoNewline -ForegroundColor White; insoptiwrht "imported" -NoNewline -ForegroundColor Green; insoptiwrht " & " -NoNewline -ForegroundColor White; insoptiwrht "activated" -NoNewline -ForegroundColor Green; insoptiwrht " ! " -NoNewline -ForegroundColor White; insoptiwrht "(GUID : $insoptiguid)" -ForegroundColor DarkGray; Start-Process "control.exe" -ArgumentList "powercfg.cpl"; $insoptifound = $true; break } } }
        if ($insoptifound) { powercfg -attributes 2a737441-1930-4402-8d77-b2bebba308a3 48e6b7a6-50f5-4782-a5d4-53bb8f07e226 -ATTRIB_HIDE | Out-Null; powercfg -attributes 2a737441-1930-4402-8d77-b2bebba308a3 d4e98f31-5ffe-4ce1-be31-1b38b384c009 -ATTRIB_HIDE | Out-Null; powercfg -attributes 2a737441-1930-4402-8d77-b2bebba308a3 0853a681-27c8-4100-a2fd-82013e970683 -ATTRIB_HIDE | Out-Null; powercfg /SETACVALUEINDEX $insoptiguid 2a737441-1930-4402-8d77-b2bebba308a3 48e6b7a6-50f5-4782-a5d4-53bb8f07e226 0 | Out-Null; powercfg /SETDCVALUEINDEX $insoptiguid 2a737441-1930-4402-8d77-b2bebba308a3 48e6b7a6-50f5-4782-a5d4-53bb8f07e226 0 | Out-Null; powercfg /SETACVALUEINDEX $insoptiguid 2a737441-1930-4402-8d77-b2bebba308a3 d4e98f31-5ffe-4ce1-be31-1b38b384c009 0 | Out-Null; powercfg /SETDCVALUEINDEX $insoptiguid 2a737441-1930-4402-8d77-b2bebba308a3 d4e98f31-5ffe-4ce1-be31-1b38b384c009 0 | Out-Null; powercfg -attributes 54533251-82be-4824-96c1-47b60b740d00 465e1f50-b610-473a-ab58-00d1077dc418 -ATTRIB_HIDE | Out-Null; powercfg -attributes 54533251-82be-4824-96c1-47b60b740d00 619b7505-003b-4e82-b7a6-4dd29c300971 -ATTRIB_HIDE | Out-Null; powercfg -attributes 54533251-82be-4824-96c1-47b60b740d00 be337238-0d82-4146-a960-4f3749d470c7 -ATTRIB_HIDE | Out-Null } else { Write-Log -Type "!" -TypeColor Red -Message "The insopti-PowerPlan plan could not be activated." -MessageColor Red; Show-DynamicCountdown -Seconds 2 -Message "Continuing" -IconColor Red }
    }
    catch { Write-Log -Type "!" -TypeColor Red -Message "An error has occurred : $_" -MessageColor Red; Show-DynamicCountdown -Seconds 2 -Message "Continuing" -IconColor Red }
    finally { Remove-Item $insoptibannerScriptPath, $insoptipowerPlanPath -Force -ErrorAction SilentlyContinue; insoptiexitmainmenu }
}

function insoptiexitmainmenu { Write-Log -Type "+" -TypeColor Green -Message "Thanks for using this tool !"; Write-Log -Type "+" -TypeColor Green -Message "Enter your choice:"; insoptiwrht ""; insoptiwrht " [" -ForegroundColor Blue -NoNewline; insoptiwrht "1" -ForegroundColor White -NoNewline; insoptiwrht "] Exit" -ForegroundColor Blue; insoptiwrht " [" -ForegroundColor Blue -NoNewline; insoptiwrht "2" -ForegroundColor White -NoNewline; insoptiwrht "] Go to Discord" -ForegroundColor Blue; insoptiwrht " > " -ForegroundColor Cyan -NoNewline; $insoptiChoice = Read-Host; switch ($insoptiChoice) { "1" { insoptiquit2 } "2" { insoptiDiscord } default { Write-Log -Type "!" -TypeColor Yellow -Message "Invalid choice." -MessageColor Yellow; Show-DynamicCountdown -Seconds 2 -Message "Retrying" -IconColor Yellow; Clear-Host; insoptiexitmainmenu } } }
function insoptiDiscord { param([string]$insoptiURL="https://guns.lol/inso.vs"); try { Start-Process -FilePath $insoptiURL; $Host.UI.RawUI.CursorPosition=@{X=0;Y=($Host.UI.RawUI.CursorPosition.Y - 1)}; Write-Log -Type "+" -TypeColor Green -Message "Guns profile page has been opened successfully." -MessageColor Green } catch { Write-Log -Type "!" -TypeColor Red -Message "Error opening the page: $_" -MessageColor Red }; Show-DynamicCountdown -Seconds 2 -Message "Closing" -IconColor Green; insoptiquit2 }
function insoptiquit2 { Clear-Host; Write-Log -Type "!" -TypeColor Yellow -Message "Script terminated." -MessageColor Yellow; $insoptiDotCount = 0; while ($insoptiDotCount -lt 3) { $Host.UI.RawUI.CursorPosition=@{X=0;Y=($Host.UI.RawUI.CursorPosition.Y)}; insoptiwrht " [" -ForegroundColor blue -NoNewline; insoptiwrht "!" -ForegroundColor Yellow -NoNewline; insoptiwrht "] Closing the script$('.' * ($insoptiDotCount + 1))     " -ForegroundColor Yellow -NoNewline; Start-Sleep -Milliseconds 300; $insoptiDotCount++ }; exit } ;insopti
#https://guns.lol/inso.vs